/* Curated recognisability, in two grades.
 *
 * Population is a poor proxy for whether a player can place a city. Kinshasa
 * has more people than Rome, and Sao Paulo more than New York, but that is not
 * how the difficulty of a geography question works. These lists carry the
 * judgement that population cannot, and they, not population, decide the early
 * rounds.
 */

// Round-one material: placeable by a general audience without hesitation.
const HOUSEHOLD = [
  "London|GB", "Paris|FR", "New York|US", "Tokyo|JP", "Rome|IT", "Moscow|RU", "Beijing|CN",
  "Cairo|EG", "Sydney|AU", "Los Angeles|US", "Berlin|DE", "Madrid|ES", "Barcelona|ES",
  "Rio de Janeiro|BR", "São Paulo|BR", "Sao Paulo|BR", "Toronto|CA", "Chicago|US",
  "San Francisco|US", "Amsterdam|NL", "Dublin|IE", "Athens|GR", "Lisbon|PT", "Vienna|AT",
  "Prague|CZ", "Venice|IT", "Milan|IT", "Munich|DE", "Istanbul|TR", "Dubai|AE", "Hong Kong|HK",
  "Singapore|SG", "Mumbai|IN", "Delhi|IN", "New Delhi|IN", "Shanghai|CN", "Bangkok|TH",
  "Seoul|KR", "Mexico City|MX", "Buenos Aires|AR", "Havana|CU", "Jerusalem|IL", "Las Vegas|US",
  "Miami|US", "Boston|US", "Washington, D.C.|US", "Seattle|US", "Vancouver|CA", "Montreal|CA",
  "Cape Town|ZA", "Johannesburg|ZA", "Nairobi|KE", "Marrakesh|MA", "Casablanca|MA",
  "Honolulu|US", "Copenhagen|DK", "Stockholm|SE", "Oslo|NO", "Helsinki|FI", "Brussels|BE",
  "Zurich|CH", "Geneva|CH", "Edinburgh|GB", "Manchester|GB", "Naples|IT", "Florence|IT",
  "Warsaw|PL", "Budapest|HU", "Osaka|JP", "Kyoto|JP", "Jakarta|ID", "Manila|PH",
  "Kuala Lumpur|MY", "Lagos|NG", "Tel Aviv|IL", "Lima|PE", "Bogotá|CO", "Santiago|CL",
  "Houston|US", "Philadelphia|US", "Dallas|US", "Atlanta|US", "Denver|US", "New Orleans|US",
  "San Diego|US", "Phoenix|US",
];

// Widely heard of, but not necessarily placeable on sight.
const KNOWN = [
  "Liverpool|GB", "Marseille|FR", "Lyon|FR", "Nice|FR", "Bordeaux|FR", "Toulouse|FR",
  "Cannes|FR", "Monaco|MC", "Valencia|ES", "Seville|ES", "Sevilla|ES", "Bilbao|ES", "Málaga|ES",
  "Palma|ES", "Lisboa|PT", "Porto|PT", "Roma|IT", "Milano|IT", "Napoli|IT", "Turin|IT",
  "Torino|IT", "Venezia|IT", "Firenze|IT", "Bologna|IT", "Palermo|IT", "Pisa|IT", "Verona|IT",
  "München|DE", "Hamburg|DE", "Frankfurt am Main|DE", "Cologne|DE", "Köln|DE", "Düsseldorf|DE",
  "Stuttgart|DE", "Dresden|DE", "Leipzig|DE", "Nuremberg|DE", "Wien|AT", "Salzburg|AT",
  "Innsbruck|AT", "Zürich|CH", "Genève|CH", "Bern|CH", "Basel|CH", "Rotterdam|NL",
  "The Hague|NL", "Utrecht|NL", "Bruxelles|BE", "Antwerp|BE", "Bruges|BE", "Brugge|BE",
  "Luxembourg|LU", "København|DK", "Bergen|NO", "Gothenburg|SE", "Göteborg|SE", "Reykjavík|IS",
  "Reykjavik|IS", "Tallinn|EE", "Riga|LV", "Vilnius|LT", "Warszawa|PL", "Kraków|PL",
  "Krakow|PL", "Gdańsk|PL", "Praha|CZ", "Brno|CZ", "Bratislava|SK", "Ljubljana|SI", "Zagreb|HR",
  "Dubrovnik|HR", "Split|HR", "Sarajevo|BA", "Belgrade|RS", "Beograd|RS", "Podgorica|ME",
  "Skopje|MK", "Tirana|AL", "Pristina|XK", "Sofia|BG", "Bucharest|RO", "București|RO",
  "Chișinău|MD", "Kyiv|UA", "Kiev|UA", "Odesa|UA", "Odessa|UA", "Lviv|UA", "Minsk|BY",
  "Moskva|RU", "Saint Petersburg|RU", "Novosibirsk|RU", "Vladivostok|RU", "Sochi|RU",
  "Kazan|RU", "Yekaterinburg|RU", "Athína|GR", "Thessaloniki|GR", "Heraklion|GR",
  "Santorini|GR", "Thera|GR", "Ankara|TR", "Izmir|TR", "Antalya|TR", "Valletta|MT",
  "Nicosia|CY", "Andorra la Vella|AD", "San Marino|SM", "Vatican City|VA", "Vaduz|LI",
  "Reykjanesbaer|IS", "Belfast|GB", "Cardiff|GB", "Glasgow|GB", "Birmingham|GB", "Leeds|GB",
  "Alexandria|EG", "Luxor|EG", "Giza|EG", "Sharm el-Sheikh|EG", "Haifa|IL", "Amman|JO",
  "Petra|JO", "Beirut|LB", "Damascus|SY", "Aleppo|SY", "Baghdad|IQ", "Basra|IQ", "Erbil|IQ",
  "Tehran|IR", "Isfahan|IR", "Shiraz|IR", "Mashhad|IR", "Riyadh|SA", "Jeddah|SA", "Mecca|SA",
  "Makkah|SA", "Medina|SA", "Abu Dhabi|AE", "Doha|QA", "Kuwait City|KW", "Manama|BH",
  "Muscat|OM", "Sanaa|YE", "Sana'a|YE", "Rabat|MA", "Marrakech|MA", "Fez|MA", "Tangier|MA",
  "Algiers|DZ", "Tunis|TN", "Tripoli|LY", "Benghazi|LY", "Khartoum|SD", "Abuja|NG", "Kano|NG",
  "Accra|GH", "Abidjan|CI", "Dakar|SN", "Bamako|ML", "Timbuktu|ML", "Ouagadougou|BF",
  "Niamey|NE", "Conakry|GN", "Freetown|SL", "Monrovia|LR", "Lomé|TG", "Cotonou|BJ",
  "Yaoundé|CM", "Douala|CM", "Libreville|GA", "Brazzaville|CG", "Kinshasa|CD", "Lubumbashi|CD",
  "Luanda|AO", "Windhoek|NA", "Gaborone|BW", "Harare|ZW", "Victoria Falls|ZW", "Lusaka|ZM",
  "Lilongwe|MW", "Maputo|MZ", "Antananarivo|MG", "Port Louis|MU", "Victoria|SC", "Moroni|KM",
  "Durban|ZA", "Pretoria|ZA", "Maseru|LS", "Mbabane|SZ", "Mombasa|KE", "Kampala|UG",
  "Kigali|RW", "Bujumbura|BI", "Dodoma|TZ", "Dar es Salaam|TZ", "Zanzibar|TZ", "Addis Ababa|ET",
  "Asmara|ER", "Djibouti|DJ", "Mogadishu|SO", "Juba|SS", "N'Djamena|TD", "Bangui|CF",
  "Yokohama|JP", "Sapporo|JP", "Hiroshima|JP", "Nagoya|JP", "Fukuoka|JP", "Okinawa|JP",
  "Naha|JP", "Busan|KR", "Incheon|KR", "Pyongyang|KP", "Macau|MO", "Macao|MO", "Guangzhou|CN",
  "Shenzhen|CN", "Chengdu|CN", "Xi'an|CN", "Chongqing|CN", "Wuhan|CN", "Harbin|CN",
  "Kunming|CN", "Lhasa|CN", "Urumqi|CN", "Qingdao|CN", "Tianjin|CN", "Taipei|TW",
  "Kaohsiung|TW", "Ulaanbaatar|MN", "Hanoi|VN", "Ho Chi Minh City|VN", "Da Nang|VN",
  "Chiang Mai|TH", "Phuket|TH", "Phnom Penh|KH", "Siem Reap|KH", "Vientiane|LA", "Yangon|MM",
  "Naypyidaw|MM", "Mandalay|MM", "Penang|MY", "George Town|MY", "Bali|ID", "Denpasar|ID",
  "Surabaya|ID", "Bandung|ID", "Medan|ID", "Cebu City|PH", "Davao|PH", "Bandar Seri Begawan|BN",
  "Dili|TL", "Bangalore|IN", "Bengaluru|IN", "Kolkata|IN", "Chennai|IN", "Hyderabad|IN",
  "Jaipur|IN", "Agra|IN", "Varanasi|IN", "Goa|IN", "Kochi|IN", "Pune|IN", "Ahmedabad|IN",
  "Karachi|PK", "Lahore|PK", "Islamabad|PK", "Peshawar|PK", "Dhaka|BD", "Chittagong|BD",
  "Kathmandu|NP", "Thimphu|BT", "Colombo|LK", "Malé|MV", "Male|MV", "Kabul|AF", "Kandahar|AF",
  "Tashkent|UZ", "Samarkand|UZ", "Bukhara|UZ", "Astana|KZ", "Nur-Sultan|KZ", "Almaty|KZ",
  "Bishkek|KG", "Dushanbe|TJ", "Ashgabat|TM", "Baku|AZ", "Tbilisi|GE", "Yerevan|AM",
  "Melbourne|AU", "Brisbane|AU", "Perth|AU", "Adelaide|AU", "Canberra|AU", "Darwin|AU",
  "Hobart|AU", "Cairns|AU", "Gold Coast|AU", "Auckland|NZ", "Wellington|NZ", "Christchurch|NZ",
  "Queenstown|NZ", "Suva|FJ", "Nadi|FJ", "Port Moresby|PG", "Nouméa|NC", "Papeete|PF",
  "Apia|WS", "Nuku'alofa|TO", "Port Vila|VU", "Honiara|SB", "Tarawa|KI", "Funafuti|TV",
  "Majuro|MH", "Palikir|FM", "Ngerulmud|PW", "Yaren|NR", "Hagåtña|GU", "Pago Pago|AS",
  "Avarua|CK", "New York City|US", "San Antonio|US", "Washington|US", "Detroit|US",
  "Minneapolis|US", "Portland|US", "Nashville|US", "Austin|US", "Salt Lake City|US",
  "Anchorage|US", "Orlando|US", "Pittsburgh|US", "Cleveland|US", "St. Louis|US",
  "Kansas City|US", "Baltimore|US", "Sacramento|US", "Albuquerque|US", "Montréal|CA",
  "Calgary|CA", "Ottawa|CA", "Edmonton|CA", "Quebec City|CA", "Québec|CA", "Winnipeg|CA",
  "Halifax|CA", "Whitehorse|CA", "Yellowknife|CA", "Guadalajara|MX", "Monterrey|MX",
  "Cancún|MX", "Cancun|MX", "Tijuana|MX", "Oaxaca|MX", "Mérida|MX", "Acapulco|MX", "Puebla|MX",
  "La Habana|CU", "Nassau|BS", "Kingston|JM", "Port-au-Prince|HT", "Santo Domingo|DO",
  "San Juan|PR", "Bridgetown|BB", "Port of Spain|TT", "Castries|LC", "St. George's|GD",
  "Roseau|DM", "Basseterre|KN", "St. John's|AG", "Kingstown|VC", "Belmopan|BZ",
  "Guatemala City|GT", "San Salvador|SV", "Tegucigalpa|HN", "Managua|NI", "San José|CR",
  "Panama City|PA", "Nuuk|GL", "Hamilton|BM", "Willemstad|CW", "Oranjestad|AW",
  "George Town|KY", "Brasília|BR", "Brasilia|BR", "Salvador|BR", "Recife|BR", "Fortaleza|BR",
  "Manaus|BR", "Belo Horizonte|BR", "Porto Alegre|BR", "Curitiba|BR", "Córdoba|AR",
  "Rosario|AR", "Mendoza|AR", "Ushuaia|AR", "Bariloche|AR", "Valparaíso|CL", "Punta Arenas|CL",
  "Cusco|PE", "Cuzco|PE", "Arequipa|PE", "Quito|EC", "Guayaquil|EC", "Bogota|CO", "Medellín|CO",
  "Cartagena|CO", "Cali|CO", "Caracas|VE", "Maracaibo|VE", "La Paz|BO", "Sucre|BO",
  "Santa Cruz de la Sierra|BO", "Asunción|PY", "Montevideo|UY", "Georgetown|GY",
  "Paramaribo|SR", "Cayenne|GF", "Stanley|FK",
];

module.exports = { household: HOUSEHOLD, known: KNOWN };
